/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OfficerModule.Attendece;

// import necessary packages

import OfficerModule.Officer;
import admin.TableOperations;
import com.toedter.calendar.JDateChooser;
import common.code.Auth;
import common.code.MyDbConnector;
import common.code.UserProfile;
import java.awt.Image;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class UpdateAttendence extends javax.swing.JFrame  {
    PreparedStatement pst4,pst3 = null;
    //ResultSet rs1;
     Connection conn = null;
    private String email;
    private Officer officerAcc;
    private MyDbConnector dbConnector;
    private Connection connection;   
    String student;
    UserProfile loggedUser = Auth.getLoggedUser();
    //code end import image
    
    public UpdateAttendence(Officer officerAcc) {
        initComponents();
        dbConnector = new MyDbConnector();
        connection = dbConnector.getMyConnection();
        this.officerAcc = officerAcc;
    }

    private UpdateAttendence() {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_copy2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        stuID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ViewData = new javax.swing.JButton();
        ReseData = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        updateTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        s_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DateNew = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dep = new javax.swing.JComboBox<>();
        yearr = new javax.swing.JComboBox<>();
        Statuss = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1260, 820));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(104, 164, 236));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_copy2.setBackground(new java.awt.Color(255, 255, 255));
        txt_copy2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_copy2.setForeground(new java.awt.Color(255, 255, 255));
        txt_copy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_copy2.setText("© Faculty of Technology,University of Ruhuna.");
        jPanel1.add(txt_copy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText(" ATTENDENCE UPDATE PORTAL");
        jLabel10.setFocusable(false);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel10.setInheritsPopupMenu(false);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 370, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backbtn.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setMinimumSize(new java.awt.Dimension(1070, 420));
        jPanel4.setPreferredSize(new java.awt.Dimension(1070, 420));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(stuID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 110, -1));

        ViewData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ViewData.setText("VIEW");
        ViewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDataActionPerformed(evt);
            }
        });
        jPanel4.add(ViewData, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 120, 30));

        ReseData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReseData.setText("RESET");
        ReseData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReseDataActionPerformed(evt);
            }
        });
        jPanel4.add(ReseData, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 110, 30));

        updateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Cource ID", "Depatment", "Date", "Level", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(updateTable);
        if (updateTable.getColumnModel().getColumnCount() > 0) {
            updateTable.getColumnModel().getColumn(0).setPreferredWidth(250);
            updateTable.getColumnModel().getColumn(1).setPreferredWidth(250);
            updateTable.getColumnModel().getColumn(2).setPreferredWidth(250);
            updateTable.getColumnModel().getColumn(3).setPreferredWidth(250);
            updateTable.getColumnModel().getColumn(4).setPreferredWidth(250);
            updateTable.getColumnModel().getColumn(5).setPreferredWidth(250);
        }

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 660, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Student ID");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        s_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_idActionPerformed(evt);
            }
        });
        jPanel4.add(s_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Course ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));
        jPanel4.add(c_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Date");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 60, -1));

        DateNew.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(DateNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Department");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Level");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 80, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Status");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));

        dep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "ICT", "BST", "ET" }));
        jPanel4.add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 120, -1));

        yearr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yearr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "LEVEL 1", "LEVEL 2", "LEVEL 3", "LEVEL 4" }));
        jPanel4.add(yearr, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 120, -1));

        Statuss.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Statuss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Absent", "Present" }));
        jPanel4.add(Statuss, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 120, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 120, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 120, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1250, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1260, 490));

        setSize(new java.awt.Dimension(1266, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void updatedata(String student){
        
        try{
            Statement st =connection.createStatement();
            String sql = "select * from attendance WHERE userID='"+student+"'";
            ResultSet rs= st.executeQuery(sql);
            
                      
            while(rs.next()){
                String Student_id = rs.getString("userID");
                String Course_id = rs.getString("CourseID");
                String department= rs.getString("Department");
                String date=rs.getString("Date");
                String years=rs.getString("Year");
                String status= rs.getString("Status");
                
                String tbData[]={Student_id,Course_id,department,date,years,status};
               
                DefaultTableModel model = (DefaultTableModel) updateTable.getModel();
                int rowCount = model.getRowCount();
                for (int i = rowCount - 1; i >= 0; i--) {
                boolean isEmptyRow = true;
                for (int j = 0; j < model.getColumnCount(); j++) {
                Object value = model.getValueAt(i, j);
                if (value != null && !value.toString().isEmpty()) {
                isEmptyRow = false;
                break;
                }
             }
                 if (isEmptyRow) {
                 model.removeRow(i);
            }
        }
                model.addRow(tbData);
                
                s_id.setText(Student_id);
                c_id.setText(Course_id);
            }
            
           
            }catch(SQLException e ){
            JOptionPane.showMessageDialog(null, e);
        }
}  
    
    public void clear(){
        stuID.setText(""); 
        s_id.setText("");
        DefaultTableModel model = (DefaultTableModel) updateTable.getModel();
        model.setRowCount(0); 
        dep.setSelectedItem("Select");
        yearr.setSelectedItem("Select");
        Statuss.setSelectedItem("Select");
        c_id.setText("");
        DateNew.setDate(null);
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String S_id = s_id.getText();
        String dept=(String)dep.getSelectedItem();
        String C_id = c_id.getText();
        String status=(String)Statuss.getSelectedItem();
        String year =(String) yearr.getSelectedItem();

        // assume user has selected a date from the date chooser
        java.util.Date selectedDate = DateNew.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = dateFormat.format(selectedDate);

        System.out.println("SIDDD   "+S_id);
        System.out.println("dep "+dept);
        System.out.println("c_id "+C_id);
        System.out.println("status "+status);
        System.out.println("year "+year);
        System.out.println("dateStrinng "+dateString);
        
        try {
            String sql2="UPDATE attendance SET CourseID='"+C_id+"',Department='"+dept+"',Date='"+dateString+"',Status='"+status+"',Year='"+year+"' WHERE userID='"+S_id+"'";
            pst3 =connection.prepareStatement(sql2);
            pst3.execute();
            DefaultTableModel model = (DefaultTableModel) updateTable.getModel();
            model.setRowCount(0);
            updatedata(student);

        } catch (SQLException ex) {
            Logger.getLogger(UpdateAttendence.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void s_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_idActionPerformed

    private void ReseDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReseDataActionPerformed
        clear();

    }//GEN-LAST:event_ReseDataActionPerformed

    private void ViewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDataActionPerformed
        System.out.println("bbbhbbbbbbbbbbbb");
        student = stuID.getText();
        System.out.println("student "+student);
        try{
            updatedata(student);
        }catch(Exception e){
            System.out.println("not go update statement");
        }
        
    }//GEN-LAST:event_ViewDataActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        officerAcc.back(officerAcc);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAttendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAttendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAttendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAttendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAttendence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateNew;
    private javax.swing.JButton ReseData;
    private javax.swing.JComboBox<String> Statuss;
    private javax.swing.JButton ViewData;
    private javax.swing.JTextField c_id;
    private javax.swing.JComboBox<String> dep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField s_id;
    private javax.swing.JTextField stuID;
    private javax.swing.JLabel txt_copy2;
    private javax.swing.JTable updateTable;
    private javax.swing.JComboBox<String> yearr;
    // End of variables declaration//GEN-END:variables

} 

  
  
