/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lecturer.gui;

import common.code.Auth;
import common.code.AvatarGenerator;
import common.code.DashboardOperation;
import common.code.MyDbConnector;
import common.code.UserProfile;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lecturer.Lecturer;
import notice.GlassPanePopup;
import notice.NoticeDatabase;

/**
 *
 * @author kavin
 */
public class LecturerDashboard extends javax.swing.JFrame implements DashboardOperation{
    
    private Lecturer lecturer;
    
    private String student_count;
    private String courses_count;
    
    private MyDbConnector dbConnector;
    Connection connection = null;
    
    UserProfile loggedUser = Auth.getLoggedUser();
    byte[] profilePicture = loggedUser.getProfilePicture();
    String email = loggedUser.getEmail();
    
    private GlassPanePopup glassPanePopup;
    private JPanel contentPane;

    /**
     * Creates new form LecturerDashboard
     */
    public LecturerDashboard() {
        
    }

    public LecturerDashboard(Lecturer lecturer) {
        this.lecturer = lecturer;
        dbConnector = new MyDbConnector();
        initComponents();
        userCounts();
        setAvatar();
        updateEmail();
    }
    
    @Override
    public void setAvatar() {
        ImageIcon avatar = AvatarGenerator.getAvatar(profilePicture);
        avatarLabel.setIcon(avatar);
    }

    @Override
    public void updateEmail(){
        lable_userEmail.setText(loggedUser.getEmail());
    }
    
    /**
     * Retrieves and displays the count of students and courses from the database.
     */
    public void userCounts() {
        PreparedStatement pst1 = null;
        PreparedStatement pst2 = null;
        ResultSet rs1, rs2;
        int stu_count = 0, course_count = 0;

        try {
            dbConnector = new MyDbConnector();
            System.out.println("Succeed...");
            try {
                connection = dbConnector.getMyConnection();

                String sql1 = "SELECT COUNT(id) FROM `userprofiles` WHERE userType = 'student'";
                pst1 = connection.prepareStatement(sql1);
                rs1 = pst1.executeQuery();

                String sql2 = "SELECT COUNT(CourseID) FROM `coursedetails`";
                pst2 = connection.prepareStatement(sql2);
                rs2 = pst2.executeQuery();

                if (rs1.next()) {
                    stu_count = rs1.getInt(1);
                }
                if (rs2.next()) {
                    course_count = rs2.getInt(1);
                }

                student_count = Integer.toString(stu_count);
                courses_count = Integer.toString(course_count);
                student_count = Integer.toString(stu_count);

                sttuu_count.setText(student_count);  
                coursse_count.setText(courses_count);

                System.out.println("Student count: " + student_count);
                System.out.println("Courses count: " + courses_count);
            } catch (Exception e) {
                System.out.println("Getting error connect...");
            } finally {
                if (connection != null) {
                    try {
                        connection.close();
                        System.out.println("Close....");
                    } catch (SQLException e) {
                        System.out.println("Error in closing the connection: " + e.getMessage());
                    }
                }
            } 
        } catch (Exception e) {
            System.out.println("dbConnector not assigned.." + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        avatarLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_courseDetails = new javax.swing.JButton();
        sttuu_count = new javax.swing.JLabel();
        course = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_stdDet = new javax.swing.JButton();
        coursse_count = new javax.swing.JLabel();
        stu = new javax.swing.JLabel();
        btn_stdAtten = new javax.swing.JButton();
        btn_Med = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        marks = new javax.swing.JLabel();
        btn_stdMarks = new javax.swing.JButton();
        btn_batchMarks = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btn_stdMarks2 = new javax.swing.JButton();
        btn_stdMarks1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        notification = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        lable_userEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(104, 164, 236));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_courseDetails.setBackground(new java.awt.Color(11, 83, 148));
        btn_courseDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_courseDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_courseDetails.setText("MANAGE");
        btn_courseDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_courseDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(btn_courseDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 240, 40));

        sttuu_count.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        sttuu_count.setText("10");
        jPanel5.add(sttuu_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/course box.png"))); // NOI18N
        course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                courseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                courseMouseExited(evt);
            }
        });
        jPanel5.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 130));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 260, 270));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_stdDet.setBackground(new java.awt.Color(11, 83, 148));
        btn_stdDet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_stdDet.setForeground(new java.awt.Color(255, 255, 255));
        btn_stdDet.setText("VIEW DETAILS");
        btn_stdDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stdDetActionPerformed(evt);
            }
        });
        jPanel6.add(btn_stdDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 240, 40));

        coursse_count.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        coursse_count.setText("10");
        jPanel6.add(coursse_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        stu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student box.png"))); // NOI18N
        stu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stuMouseExited(evt);
            }
        });
        jPanel6.add(stu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 130));

        btn_stdAtten.setBackground(new java.awt.Color(11, 83, 148));
        btn_stdAtten.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_stdAtten.setForeground(new java.awt.Color(255, 255, 255));
        btn_stdAtten.setText("ATTENDANCE");
        btn_stdAtten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stdAttenActionPerformed(evt);
            }
        });
        jPanel6.add(btn_stdAtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 240, 40));

        btn_Med.setBackground(new java.awt.Color(11, 83, 148));
        btn_Med.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Med.setForeground(new java.awt.Color(255, 255, 255));
        btn_Med.setText("MEDICAL RECORDS");
        btn_Med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MedActionPerformed(evt);
            }
        });
        jPanel6.add(btn_Med, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 240, 40));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 360));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/marks box.png"))); // NOI18N
        marks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                marksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                marksMouseExited(evt);
            }
        });
        jPanel8.add(marks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 130));

        btn_stdMarks.setBackground(new java.awt.Color(11, 83, 148));
        btn_stdMarks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_stdMarks.setForeground(new java.awt.Color(255, 255, 255));
        btn_stdMarks.setText("CALCULATE");
        btn_stdMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stdMarksActionPerformed(evt);
            }
        });
        jPanel8.add(btn_stdMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 240, 40));

        btn_batchMarks.setBackground(new java.awt.Color(11, 83, 148));
        btn_batchMarks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_batchMarks.setForeground(new java.awt.Color(255, 255, 255));
        btn_batchMarks.setText("VIEW MARKS");
        btn_batchMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batchMarksActionPerformed(evt);
            }
        });
        jPanel8.add(btn_batchMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 240, 40));

        jPanel9.setBackground(new java.awt.Color(11, 83, 148));

        btn_stdMarks2.setBackground(new java.awt.Color(11, 83, 148));
        btn_stdMarks2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_stdMarks2.setForeground(new java.awt.Color(255, 255, 255));
        btn_stdMarks2.setText("CA MARKS ");
        btn_stdMarks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stdMarks2ActionPerformed(evt);
            }
        });

        btn_stdMarks1.setBackground(new java.awt.Color(11, 83, 148));
        btn_stdMarks1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_stdMarks1.setForeground(new java.awt.Color(255, 255, 255));
        btn_stdMarks1.setText("FINAL MARKS ");
        btn_stdMarks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stdMarks1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADD MARKS");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_stdMarks2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_stdMarks1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_stdMarks2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_stdMarks1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 260, 370));

        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/notification.png"))); // NOI18N
        notification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificationMouseClicked(evt);
            }
        });
        jPanel4.add(notification, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 100, 80));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 260, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, 630));

        jPanel3.setBackground(new java.awt.Color(104, 164, 236));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setBackground(new java.awt.Color(11, 83, 148));
        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel3.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 310, 50));

        btn_edit.setBackground(new java.awt.Color(11, 83, 148));
        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("EDIT PROFILE");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel3.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 310, 50));

        lable_userEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lable_userEmail.setForeground(new java.awt.Color(255, 255, 255));
        lable_userEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable_userEmail.setText("Lecturer@gmail.com");
        lable_userEmail.setToolTipText("");
        jPanel3.add(lable_userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 310, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("© Faculty of Technology,");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("University of Ruhuna.");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lecturer Pannel");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuMouseEntered
        stu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student round.png")));
    }//GEN-LAST:event_stuMouseEntered

    private void stuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuMouseExited
        stu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student box.png")));
    }//GEN-LAST:event_stuMouseExited

    private void courseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseEntered
        course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/course round.png")));
    }//GEN-LAST:event_courseMouseEntered

    private void courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseExited
        course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/course box.png")));
    }//GEN-LAST:event_courseMouseExited

    private void notificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationMouseClicked
        if (glassPanePopup == null || !glassPanePopup.isVisible()) {
            glassPanePopup = new GlassPanePopup();
            setGlassPane(glassPanePopup);
            glassPanePopup.showPopup(NoticeDatabase.getNotices());
            getGlassPane().setVisible(true);
        }
    }//GEN-LAST:event_notificationMouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
    int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirmation", JOptionPane.YES_NO_OPTION);
    if (result == JOptionPane.YES_OPTION) {
        this.dispose();
        lecturer.logout();
    }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        lecturer.updateUserProfile(lecturer);
        this.dispose();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_courseDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_courseDetailsActionPerformed
        lecturer.updateCourseModule(lecturer);
        this.dispose();
    }//GEN-LAST:event_btn_courseDetailsActionPerformed

    private void btn_stdDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stdDetActionPerformed
        lecturer.ViewStudentDetails(lecturer);
        this.dispose();
    }//GEN-LAST:event_btn_stdDetActionPerformed

    private void btn_stdAttenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stdAttenActionPerformed
        lecturer.ViewStudentAttendance(lecturer);
        this.dispose();
    }//GEN-LAST:event_btn_stdAttenActionPerformed

    private void btn_stdMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stdMarksActionPerformed
        lecturer.ViewStudentMarks(lecturer);
        this.dispose();
    }//GEN-LAST:event_btn_stdMarksActionPerformed

    private void btn_batchMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batchMarksActionPerformed
        lecturer.viewWholeMarks(lecturer);
        this.dispose();
    }//GEN-LAST:event_btn_batchMarksActionPerformed

    private void btn_MedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MedActionPerformed
        lecturer.ViewStudentMedical(lecturer);
        this.dispose();
    }//GEN-LAST:event_btn_MedActionPerformed

    private void marksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marksMouseEntered
        marks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/marks round.png")));
    }//GEN-LAST:event_marksMouseEntered

    private void marksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marksMouseExited
        marks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/marks box.png")));
    }//GEN-LAST:event_marksMouseExited

    private void btn_stdMarks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stdMarks1ActionPerformed
        lecturer.AddFinMarks(lecturer);
        this.dispose();
    }//GEN-LAST:event_btn_stdMarks1ActionPerformed

    private void btn_stdMarks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stdMarks2ActionPerformed
        lecturer.AddCA(lecturer);
        this.dispose();
    }//GEN-LAST:event_btn_stdMarks2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerDashboard().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarLabel;
    private javax.swing.JButton btn_Med;
    private javax.swing.JButton btn_batchMarks;
    private javax.swing.JButton btn_courseDetails;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_stdAtten;
    private javax.swing.JButton btn_stdDet;
    private javax.swing.JButton btn_stdMarks;
    private javax.swing.JButton btn_stdMarks1;
    private javax.swing.JButton btn_stdMarks2;
    private javax.swing.JLabel course;
    private javax.swing.JLabel coursse_count;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lable_userEmail;
    private javax.swing.JLabel marks;
    private javax.swing.JLabel notification;
    private javax.swing.JLabel sttuu_count;
    private javax.swing.JLabel stu;
    // End of variables declaration//GEN-END:variables
}
